namespace Code_NT106.Q14._2_Lab05_Group3_24521557_24520331_24521560_24521538_24521213
{
    partial class Bai05
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            groupBoxSend = new System.Windows.Forms.GroupBox();
            btnChonAnh = new System.Windows.Forms.Button();
            btnGuiDongGop = new System.Windows.Forms.Button();
            txtHinhAnh = new System.Windows.Forms.TextBox();
            txtTenMonAn = new System.Windows.Forms.TextBox();
            txtSenderAppPassword = new System.Windows.Forms.TextBox();
            txtSenderEmail = new System.Windows.Forms.TextBox();
            lblHinhAnh = new System.Windows.Forms.Label();
            lblTenMon = new System.Windows.Forms.Label();
            lblAppPass = new System.Windows.Forms.Label();
            lblSenderEmail = new System.Windows.Forms.Label();
            pictureBoxPreview = new System.Windows.Forms.PictureBox();
            groupBox2 = new System.Windows.Forms.GroupBox();
            listViewMonAn = new System.Windows.Forms.ListView();
            colIDMA = new System.Windows.Forms.ColumnHeader();
            colTenMonAn = new System.Windows.Forms.ColumnHeader();
            colHinhAnh = new System.Windows.Forms.ColumnHeader();
            colNguoiDongGop = new System.Windows.Forms.ColumnHeader();
            groupBoxImport = new System.Windows.Forms.GroupBox();
            btnTaiDongGop = new System.Windows.Forms.Button();
            btnTimMonAn = new System.Windows.Forms.Button();
            btnXoa = new System.Windows.Forms.Button();
            btnThoat = new System.Windows.Forms.Button();
            groupBox3 = new System.Windows.Forms.GroupBox();
            pictureBoxMonAn = new System.Windows.Forms.PictureBox();
            lblKetQua = new System.Windows.Forms.Label();
            label4 = new System.Windows.Forms.Label();
            openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            groupBoxSend.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(pictureBoxPreview)).BeginInit();
            groupBox2.SuspendLayout();
            groupBoxImport.SuspendLayout();
            groupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(pictureBoxMonAn)).BeginInit();
            SuspendLayout();
            groupBoxSend.Controls.Add(pictureBoxPreview);
            groupBoxSend.Controls.Add(btnChonAnh);
            groupBoxSend.Controls.Add(btnGuiDongGop);
            groupBoxSend.Controls.Add(txtHinhAnh);
            groupBoxSend.Controls.Add(txtTenMonAn);
            groupBoxSend.Controls.Add(txtSenderAppPassword);
            groupBoxSend.Controls.Add(txtSenderEmail);
            groupBoxSend.Controls.Add(lblHinhAnh);
            groupBoxSend.Controls.Add(lblTenMon);
            groupBoxSend.Controls.Add(lblAppPass);
            groupBoxSend.Controls.Add(lblSenderEmail);
            groupBoxSend.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            groupBoxSend.Location = new System.Drawing.Point(12, 15);
            groupBoxSend.Name = "groupBoxSend";
            groupBoxSend.Size = new System.Drawing.Size(380, 410);
            groupBoxSend.TabIndex = 0;
            groupBoxSend.TabStop = false;
            groupBoxSend.Text = "Gửi đóng góp món ăn";
            lblSenderEmail.AutoSize = true;
            lblSenderEmail.Location = new System.Drawing.Point(12, 32);
            lblSenderEmail.Name = "lblSenderEmail";
            lblSenderEmail.Size = new System.Drawing.Size(52, 20);
            lblSenderEmail.TabIndex = 0;
            lblSenderEmail.Text = "Email:";
            txtSenderEmail.Location = new System.Drawing.Point(140, 29);
            txtSenderEmail.Name = "txtSenderEmail";
            txtSenderEmail.Size = new System.Drawing.Size(220, 26);
            txtSenderEmail.TabIndex = 1;
            lblAppPass.AutoSize = true;
            lblAppPass.Location = new System.Drawing.Point(12, 72);
            lblAppPass.Name = "lblAppPass";
            lblAppPass.Size = new System.Drawing.Size(106, 20);
            lblAppPass.TabIndex = 2;
            lblAppPass.Text = "AppPassword:";
            txtSenderAppPassword.Location = new System.Drawing.Point(140, 69);
            txtSenderAppPassword.Name = "txtSenderAppPassword";
            txtSenderAppPassword.Size = new System.Drawing.Size(220, 26);
            txtSenderAppPassword.TabIndex = 3;
            txtSenderAppPassword.UseSystemPasswordChar = true;
            lblTenMon.AutoSize = true;
            lblTenMon.Location = new System.Drawing.Point(12, 112);
            lblTenMon.Name = "lblTenMon";
            lblTenMon.Size = new System.Drawing.Size(102, 20);
            lblTenMon.TabIndex = 4;
            lblTenMon.Text = "Tên món ăn:";
            txtTenMonAn.Location = new System.Drawing.Point(140, 109);
            txtTenMonAn.Name = "txtTenMonAn";
            txtTenMonAn.Size = new System.Drawing.Size(220, 26);
            txtTenMonAn.TabIndex = 5;
            lblHinhAnh.AutoSize = true;
            lblHinhAnh.Location = new System.Drawing.Point(12, 152);
            lblHinhAnh.Name = "lblHinhAnh";
            lblHinhAnh.Size = new System.Drawing.Size(120, 20);
            lblHinhAnh.TabIndex = 6;
            lblHinhAnh.Text = "Hình ảnh (URL):";
            txtHinhAnh.Location = new System.Drawing.Point(140, 149);
            txtHinhAnh.Name = "txtHinhAnh";
            txtHinhAnh.Size = new System.Drawing.Size(220, 26);
            txtHinhAnh.TabIndex = 7;
            btnChonAnh.Location = new System.Drawing.Point(140, 181);
            btnChonAnh.Name = "btnChonAnh";
            btnChonAnh.Size = new System.Drawing.Size(120, 28);
            btnChonAnh.TabIndex = 8;
            btnChonAnh.Text = "Chọn file...";
            btnChonAnh.UseVisualStyleBackColor = true;
            btnChonAnh.Click += btnChonAnh_Click;
            pictureBoxPreview.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            pictureBoxPreview.Location = new System.Drawing.Point(140, 215);
            pictureBoxPreview.Name = "pictureBoxPreview";
            pictureBoxPreview.Size = new System.Drawing.Size(220, 120);
            pictureBoxPreview.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            pictureBoxPreview.TabIndex = 10;
            pictureBoxPreview.TabStop = false;
            btnGuiDongGop.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            btnGuiDongGop.Location = new System.Drawing.Point(140, 345);
            btnGuiDongGop.Name = "btnGuiDongGop";
            btnGuiDongGop.Size = new System.Drawing.Size(160, 55);
            btnGuiDongGop.TabIndex = 9;
            btnGuiDongGop.Text = "Gửi đóng góp";
            btnGuiDongGop.UseVisualStyleBackColor = true;
            btnGuiDongGop.Click += btnGuiDongGop_Click;
            groupBox2.Controls.Add(listViewMonAn);
            groupBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            groupBox2.Location = new System.Drawing.Point(410, 15);
            groupBox2.Name = "groupBox2";
            groupBox2.Size = new System.Drawing.Size(580, 410);
            groupBox2.TabIndex = 1;
            groupBox2.TabStop = false;
            groupBox2.Text = "Danh sách món ăn";
            listViewMonAn.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] { colIDMA, colTenMonAn, colHinhAnh, colNguoiDongGop });
            listViewMonAn.FullRowSelect = true;
            listViewMonAn.GridLines = true;
            listViewMonAn.Location = new System.Drawing.Point(15, 31);
            listViewMonAn.Name = "listViewMonAn";
            listViewMonAn.Size = new System.Drawing.Size(550, 360);
            listViewMonAn.TabIndex = 0;
            listViewMonAn.UseCompatibleStateImageBehavior = false;
            listViewMonAn.View = System.Windows.Forms.View.Details;
            colIDMA.Text = "ID";
            colIDMA.Width = 50;
            colTenMonAn.Text = "Tên món ăn";
            colTenMonAn.Width = 180;
            colHinhAnh.Text = "Hình ảnh";
            colHinhAnh.Width = 170;
            colNguoiDongGop.Text = "Người đóng góp";
            colNguoiDongGop.Width = 140;
            groupBoxImport.Controls.Add(btnTaiDongGop);
            groupBoxImport.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            groupBoxImport.Location = new System.Drawing.Point(12, 435);
            groupBoxImport.Name = "groupBoxImport";
            groupBoxImport.Size = new System.Drawing.Size(978, 95);
            groupBoxImport.TabIndex = 6;
            groupBoxImport.TabStop = false;
            groupBoxImport.Text = "Tải đóng góp từ email";
            btnTaiDongGop.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            btnTaiDongGop.Location = new System.Drawing.Point(400, 28);
            btnTaiDongGop.Name = "btnTaiDongGop";
            btnTaiDongGop.Size = new System.Drawing.Size(180, 50);
            btnTaiDongGop.TabIndex = 0;
            btnTaiDongGop.Text = "Tải đóng góp";
            btnTaiDongGop.UseVisualStyleBackColor = true;
            btnTaiDongGop.Click += btnTaiDongGop_Click;
            btnTimMonAn.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            btnTimMonAn.Location = new System.Drawing.Point(120, 540);
            btnTimMonAn.Name = "btnTimMonAn";
            btnTimMonAn.Size = new System.Drawing.Size(180, 62);
            btnTimMonAn.TabIndex = 2;
            btnTimMonAn.Text = "Tìm món ăn";
            btnTimMonAn.UseVisualStyleBackColor = true;
            btnTimMonAn.Click += btnTimMonAn_Click;
            btnXoa.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F);
            btnXoa.Location = new System.Drawing.Point(420, 540);
            btnXoa.Name = "btnXoa";
            btnXoa.Size = new System.Drawing.Size(142, 62);
            btnXoa.TabIndex = 3;
            btnXoa.Text = "Xóa Database";
            btnXoa.UseVisualStyleBackColor = true;
            btnXoa.Click += btnXoa_Click;
            btnThoat.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F);
            btnThoat.Location = new System.Drawing.Point(710, 540);
            btnThoat.Name = "btnThoat";
            btnThoat.Size = new System.Drawing.Size(120, 62);
            btnThoat.TabIndex = 4;
            btnThoat.Text = "Thoát";
            btnThoat.UseVisualStyleBackColor = true;
            btnThoat.Click += btnThoat_Click;
            groupBox3.Controls.Add(pictureBoxMonAn);
            groupBox3.Controls.Add(lblKetQua);
            groupBox3.Controls.Add(label4);
            groupBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            groupBox3.Location = new System.Drawing.Point(12, 620);
            groupBox3.Name = "groupBox3";
            groupBox3.Size = new System.Drawing.Size(978, 312);
            groupBox3.TabIndex = 5;
            groupBox3.TabStop = false;
            groupBox3.Text = "Kết quả";
            pictureBoxMonAn.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            pictureBoxMonAn.Location = new System.Drawing.Point(550, 38);
            pictureBoxMonAn.Name = "pictureBoxMonAn";
            pictureBoxMonAn.Size = new System.Drawing.Size(400, 250);
            pictureBoxMonAn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            pictureBoxMonAn.TabIndex = 2;
            pictureBoxMonAn.TabStop = false;
            lblKetQua.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Bold);
            lblKetQua.ForeColor = System.Drawing.Color.Red;
            lblKetQua.Location = new System.Drawing.Point(20, 112);
            lblKetQua.Name = "lblKetQua";
            lblKetQua.Size = new System.Drawing.Size(500, 150);
            lblKetQua.TabIndex = 1;
            lblKetQua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            label4.AutoSize = true;
            label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            label4.Location = new System.Drawing.Point(140, 50);
            label4.Name = "label4";
            label4.Size = new System.Drawing.Size(218, 25);
            label4.TabIndex = 0;
            label4.Text = "Hôm nay bạn nên ăn:";
            AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            ClientSize = new System.Drawing.Size(1002, 950);
            Controls.Add(groupBoxImport);
            Controls.Add(groupBox3);
            Controls.Add(btnThoat);
            Controls.Add(btnXoa);
            Controls.Add(btnTimMonAn);
            Controls.Add(groupBox2);
            Controls.Add(groupBoxSend);
            Name = "Bai05";
            Text = "Bài 05 – Hôm nay ăn gì? (phiên bản số 5)";
            Load += Bai05_Load;
            groupBoxSend.ResumeLayout(false);
            groupBoxSend.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(pictureBoxPreview)).EndInit();
            groupBox2.ResumeLayout(false);
            groupBoxImport.ResumeLayout(false);
            groupBox3.ResumeLayout(false);
            groupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(pictureBoxMonAn)).EndInit();
            ResumeLayout(false);
        }

        private System.Windows.Forms.GroupBox groupBoxSend;
        private System.Windows.Forms.Button btnChonAnh;
        private System.Windows.Forms.Button btnGuiDongGop;
        private System.Windows.Forms.TextBox txtHinhAnh;
        private System.Windows.Forms.TextBox txtTenMonAn;
        private System.Windows.Forms.TextBox txtSenderAppPassword;
        private System.Windows.Forms.TextBox txtSenderEmail;
        private System.Windows.Forms.Label lblHinhAnh;
        private System.Windows.Forms.Label lblTenMon;
        private System.Windows.Forms.Label lblAppPass;
        private System.Windows.Forms.Label lblSenderEmail;
        private System.Windows.Forms.PictureBox pictureBoxPreview;

        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.ListView listViewMonAn;
        private System.Windows.Forms.ColumnHeader colIDMA;
        private System.Windows.Forms.ColumnHeader colTenMonAn;
        private System.Windows.Forms.ColumnHeader colHinhAnh;
        private System.Windows.Forms.ColumnHeader colNguoiDongGop;

        private System.Windows.Forms.GroupBox groupBoxImport;
        private System.Windows.Forms.Button btnTaiDongGop;

        private System.Windows.Forms.Button btnTimMonAn;
        private System.Windows.Forms.Button btnXoa;
        private System.Windows.Forms.Button btnThoat;

        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.PictureBox pictureBoxMonAn;
        private System.Windows.Forms.Label lblKetQua;
        private System.Windows.Forms.Label label4;

        private System.Windows.Forms.OpenFileDialog openFileDialog1;
    }
}